import type { Policy, Claim, PolicyApplication, PolicyType } from '@/types/policy';

export const mockPolicies: Policy[] = [
  {
    id: 'POL001',
    userId: 'U001',
    userName: 'Rahul Sharma',
    userEmail: 'rahul@example.com',
    type: 'health',
    status: 'active',
    premium: 2500,
    coverage: 500000,
    startDate: new Date('2024-01-01'),
    endDate: new Date('2025-01-01'),
    createdAt: new Date('2024-01-01'),
    approvedAt: new Date('2024-01-01'),
    approvedBy: 'MA001',
    documents: [
      { id: 'DOC001', name: 'ID Proof.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-01-01') },
      { id: 'DOC002', name: 'Medical Report.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-01-01') },
    ],
    healthDetails: {
      preExistingConditions: [],
      smoker: false,
      height: 175,
      weight: 70,
      bloodGroup: 'O+',
    },
  },
  {
    id: 'POL002',
    userId: 'U001',
    userName: 'Rahul Sharma',
    userEmail: 'rahul@example.com',
    type: 'vehicle',
    status: 'active',
    premium: 1500,
    coverage: 300000,
    startDate: new Date('2024-03-01'),
    endDate: new Date('2025-03-01'),
    createdAt: new Date('2024-03-01'),
    approvedAt: new Date('2024-03-01'),
    approvedBy: 'MA001',
    documents: [
      { id: 'DOC003', name: 'RC Book.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-03-01') },
    ],
    vehicleDetails: {
      make: 'Maruti Suzuki',
      model: 'Swift',
      year: 2022,
      registrationNumber: 'MH-02-AB-1234',
      chassisNumber: 'MA3EED81S00734521',
    },
  },
  {
    id: 'POL003',
    userId: 'U002',
    userName: 'Priya Patel',
    userEmail: 'priya@example.com',
    type: 'life',
    status: 'pending',
    premium: 5000,
    coverage: 1000000,
    startDate: new Date('2024-06-01'),
    endDate: new Date('2034-06-01'),
    createdAt: new Date('2024-06-01'),
    documents: [
      { id: 'DOC004', name: 'ID Proof.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-06-01') },
    ],
    beneficiaries: ['Spouse', 'Child'],
  },
];

export const mockClaims: Claim[] = [
  {
    id: 'CLM001',
    policyId: 'POL001',
    userId: 'U001',
    userName: 'Rahul Sharma',
    userEmail: 'rahul@example.com',
    type: 'Medical Emergency',
    description: 'Hospitalization due to viral fever',
    amount: 25000,
    status: 'paid',
    createdAt: new Date('2024-02-15'),
    submittedAt: new Date('2024-02-15'),
    reviewedAt: new Date('2024-02-16'),
    reviewedBy: 'SA001',
    approvedAt: new Date('2024-02-16'),
    approvedBy: 'SA001',
    paidAt: new Date('2024-02-17'),
    paidAmount: 25000,
    documents: [
      { id: 'CD001', name: 'Hospital Bill.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-02-15') },
      { id: 'CD002', name: 'Discharge Summary.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-02-15') },
    ],
    incidentDate: new Date('2024-02-10'),
    incidentLocation: 'Mumbai',
  },
  {
    id: 'CLM002',
    policyId: 'POL002',
    userId: 'U001',
    userName: 'Rahul Sharma',
    userEmail: 'rahul@example.com',
    type: 'Accident',
    description: 'Vehicle damage due to accident',
    amount: 45000,
    status: 'approved',
    createdAt: new Date('2024-04-20'),
    submittedAt: new Date('2024-04-20'),
    reviewedAt: new Date('2024-04-21'),
    reviewedBy: 'MA001',
    approvedAt: new Date('2024-04-21'),
    approvedBy: 'MA001',
    documents: [
      { id: 'CD003', name: 'FIR Copy.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-04-20') },
      { id: 'CD004', name: 'Repair Estimate.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-04-20') },
    ],
    incidentDate: new Date('2024-04-18'),
    incidentLocation: 'Andheri West, Mumbai',
  },
  {
    id: 'CLM003',
    policyId: 'POL001',
    userId: 'U001',
    userName: 'Rahul Sharma',
    userEmail: 'rahul@example.com',
    type: 'Medical Emergency',
    description: 'Dental surgery',
    amount: 15000,
    status: 'pending',
    createdAt: new Date('2024-06-10'),
    submittedAt: new Date('2024-06-10'),
    documents: [
      { id: 'CD005', name: 'Dental Report.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-06-10') },
    ],
    incidentDate: new Date('2024-06-08'),
    incidentLocation: 'Mumbai',
  },
  {
    id: 'CLM004',
    policyId: 'POL003',
    userId: 'U002',
    userName: 'Priya Patel',
    userEmail: 'priya@example.com',
    type: 'Health Checkup',
    description: 'Annual health checkup reimbursement',
    amount: 8000,
    status: 'under_review',
    createdAt: new Date('2024-06-15'),
    submittedAt: new Date('2024-06-15'),
    documents: [
      { id: 'CD006', name: 'Checkup Report.pdf', url: '#', type: 'pdf', uploadedAt: new Date('2024-06-15') },
    ],
    incidentDate: new Date('2024-06-12'),
    incidentLocation: 'Bandra, Mumbai',
  },
];

export const mockPolicyApplications: PolicyApplication[] = [
  {
    id: 'APP001',
    userId: 'U003',
    userName: 'Amit Kumar',
    userEmail: 'amit@example.com',
    type: 'health',
    status: 'submitted',
    premium: 3000,
    coverage: 600000,
    duration: 12,
    createdAt: new Date('2024-06-20'),
    submittedAt: new Date('2024-06-20'),
  },
  {
    id: 'APP002',
    userId: 'U004',
    userName: 'Sneha Gupta',
    userEmail: 'sneha@example.com',
    type: 'vehicle',
    status: 'under_review',
    premium: 2000,
    coverage: 400000,
    duration: 12,
    createdAt: new Date('2024-06-18'),
    submittedAt: new Date('2024-06-18'),
    reviewedAt: new Date('2024-06-19'),
    reviewedBy: 'SA001',
  },
  {
    id: 'APP003',
    userId: 'U005',
    userName: 'Vikram Singh',
    userEmail: 'vikram@example.com',
    type: 'life',
    status: 'rejected',
    premium: 8000,
    coverage: 2000000,
    duration: 120,
    createdAt: new Date('2024-06-15'),
    submittedAt: new Date('2024-06-15'),
    reviewedAt: new Date('2024-06-16'),
    reviewedBy: 'MA001',
    rejectionReason: 'Incomplete medical history provided',
  },
];

export const policyTypeConfig: Record<PolicyType, { label: string; icon: string; color: string }> = {
  health: { label: 'Health Insurance', icon: 'Heart', color: '#ef4444' },
  life: { label: 'Life Insurance', icon: 'User', color: '#8b5cf6' },
  vehicle: { label: 'Vehicle Insurance', icon: 'Car', color: '#06b6d4' },
  home: { label: 'Home Insurance', icon: 'Home', color: '#f59e0b' },
  travel: { label: 'Travel Insurance', icon: 'Plane', color: '#10b981' },
  business: { label: 'Business Insurance', icon: 'Briefcase', color: '#ec4899' },
};
